[default.extend-words]
controle = "controle"
ser = "ser"
autor = "autor"
clientes = "clientes"
oficial = "oficial"
atual = "atual"
vai = "vai"
Comando = "Comando"
momento = "momento"
ative = "ative"
Invalidas = "Invalidas"
ignora = "ignora"
instale = "instale"
cliente = "cliente"
funcional = "funcional"
