from pydantic import BaseModel, EmailStr
from typing import Optional, List
import datetime

class UsuarioBase(BaseModel):
    email: EmailStr
    nome: str
    papel: str # "GESTOR" ou "CONSULTOR"

class UsuarioCreate(UsuarioBase):
    senha: str

class UsuarioResponse(UsuarioBase):
    id: int
    class Config:
        from_attributes = True

class LoginRequest(BaseModel):
    email: EmailStr
    senha: str

class Token(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str
    papel: str
    nome: str

class TokenData(BaseModel):
    email: Optional[str] = None
    papel: Optional[str] = None

class ContatoBase(BaseModel):
    nome: str
    telefone: str
    email: Optional[str] = None
    tipo_numero: str  # "institucional" ou "publico"

class ContatoCreate(ContatoBase):
    id: str  # UUID generated by client

class ContatoResponse(ContatoBase):
    id: str
    atualizado_em: datetime.datetime
    excluido: bool
    class Config:
        from_attributes = True

class ContatoSync(BaseModel):
    id: str
    nome: str
    telefone: str
    email: Optional[str] = None
    tipo_numero: str
    atualizado_em: str  # String ISO representation or datetime
    excluido: bool

class SyncPayload(BaseModel):
    contatos: List[ContatoSync]
