from datetime import datetime, timezone
from typing import List, Optional

from app.modules.contatos.models import Contato
from app.modules.contatos.schemas import ContatoCreate, ContatoUpdate, ContatoSync
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select


class ContatoRepository:
    """
    Repository class for managing Contato entities in the database.
    """

    def __init__(self, db: AsyncSession):
        self.db = db

    async def listar_ativos(self) -> List[Contato]:
        """
        List all active contacts (not soft-deleted).

        Returns:
            List[Contato]: A list of active Contato instances.
        """
        result = await self.db.execute(select(Contato).where(Contato.excluido == False))
        return result.scalars().all()

    async def buscar_por_id(self, contato_id: str) -> Optional[Contato]:
        """
        Fetch a contact by its ID (UUID em formato String).

        Args:
            contato_id (str): The ID of the contact to fetch.

        Returns:
            Optional[Contato]: The Contato instance if found, else None.
        """
        result = await self.db.execute(select(Contato).where(Contato.id == contato_id))
        return result.scalars().first()

    async def criar_contato(
        self, contato_in: ContatoCreate, usuario_nome: str
    ) -> Contato:
        """Create a new contact.

        Args:
            contato_in (ContatoCreate): Payload with contact data; must include an ID generated by client.
            usuario_nome (str): Identifier of the user performing the operation (currently unused).
        Returns:
            Contato: The newly created Contato instance.
        """
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        contato = Contato(
            id=str(contato_in.id),
            nome=contato_in.nome,
            telefone=contato_in.telefone,
            email=contato_in.email,
            tipo_numero=contato_in.tipo_numero,
            criado_em=now,
            atualizado_em=now,
            excluido=False,
        )
        self.db.add(contato)
        await self.db.commit()
        await self.db.refresh(contato)
        return contato

    async def atualizar_contato(
        self, contato_id: str, contato_in: ContatoUpdate, usuario_nome: str
    ) -> Optional[Contato]:
        """Update an existing contact.

        Args:
            contato_id (str): ID of the contact to update.
            contato_in (ContatoUpdate): Partial fields to update; fields omitted remain unchanged.
            usuario_nome (str): Identifier of the user performing the operation (currently unused).
        Returns:
            Optional[Contato]: Updated Contato instance if found, otherwise None.
        """
        contato = await self.buscar_por_id(contato_id)
        if not contato:
            return None
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        # Update only provided fields
        if contato_in.nome is not None:
            contato.nome = contato_in.nome
        if contato_in.telefone is not None:
            contato.telefone = contato_in.telefone
        if contato_in.email is not None:
            contato.email = contato_in.email
        if contato_in.tipo_numero is not None:
            contato.tipo_numero = contato_in.tipo_numero
        contato.atualizado_em = now
        contato.excluido = False  # Ensure not soft-deleted
        await self.db.commit()
        await self.db.refresh(contato)
        return contato

    # NOTE: The legacy method salvar_ou_atualizar is retained for backward compatibility but not used by current API.
    async def salvar_ou_atualizar(
        self, contato_in: ContatoCreate, usuario_nome: str
    ) -> Contato:
        """Legacy method: Save a new contact or update an existing one.
        """
        contato = (
            await self.buscar_por_id(str(contato_in.id)) if contato_in.id else None
        )
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        if contato:
            contato.nome = contato_in.nome
            contato.telefone = contato_in.telefone
            contato.email = contato_in.email
            contato.tipo_numero = contato_in.tipo_numero
            contato.atualizado_em = now
            contato.excluido = False
        else:
            contato = Contato(
                id=str(contato_in.id),
                nome=contato_in.nome,
                telefone=contato_in.telefone,
                email=contato_in.email,
                tipo_numero=contato_in.tipo_numero,
                criado_em=now,
                atualizado_em=now,
                excluido=False,
            )
            self.db.add(contato)
        await self.db.commit()
        await self.db.refresh(contato)
        return contato

    async def deletar_soft(self, contato_id: str, usuario_nome: str) -> bool:
        """
        Soft delete a contact by marking it as excluded.

        Args:
            contato_id (str): The ID of the contact to soft delete.
            usuario_nome (str): The name of the user performing the deletion.

        Returns:
            bool: True if the contact was successfully soft deleted, False otherwise.
        """
        contato = await self.buscar_por_id(contato_id)
        if not contato:
            return False

        contato.excluido = True
        contato.atualizado_em = datetime.now(timezone.utc).replace(tzinfo=None)

        await self.db.commit()
        return True

    async def sincronizar_lote_offline(
        self, contatos_sync: List[ContatoSync], usuario_nome: str
    ) -> List[str]:
        """
        Synchronize a batch of contacts from offline data (Dexie.js).

        Args:
            contatos_sync (List[ContatoSync]): A list of contact payloads to synchronize.
            usuario_nome (str): The name of the user performing the synchronization.

        Returns:
            List[str]: A list of IDs of the synchronized contacts.
        """
        ids_confirmados = []

        for c in contatos_sync:
            # Tratamento seguro do datetime timezone-aware vindo do schema Pydantic
            try:
                cliente_updated_at = c.atualizado_em.astimezone(timezone.utc).replace(
                    tzinfo=None
                )
            except Exception:
                cliente_updated_at = datetime.now(timezone.utc).replace(tzinfo=None)

            contato_db = await self.buscar_por_id(str(c.id)) if c.id else None

            if contato_db:
                # Normaliza a data do banco para naive UTC para comparação segura
                db_updated_at = contato_db.atualizado_em
                if db_updated_at.tzinfo is not None:
                    db_updated_at = db_updated_at.astimezone(timezone.utc).replace(tzinfo=None)

                # CONFLITO: Só aceita se a alteração do cliente offline for mais nova do que a do banco.
                if cliente_updated_at > db_updated_at:
                    contato_db.nome = c.nome
                    contato_db.telefone = c.telefone
                    contato_db.email = c.email
                    contato_db.tipo_numero = c.tipo_numero
                    contato_db.excluido = c.excluido  # Sincroniza o status de exclusão vindo do offline
                    contato_db.atualizado_em = cliente_updated_at
            else:
                # REGISTRO NOVO: Criado inteiramente offline no cliente
                novo_contato = Contato(
                    id=str(
                        c.id
                    ),  # Preserva o ID gerado pelo cliente para manter a consistência com o IndexedDB/Dexie
                    nome=c.nome,
                    telefone=c.telefone,
                    email=c.email,
                    tipo_numero=c.tipo_numero,
                    excluido=c.excluido,
                    criado_em=cliente_updated_at,
                    atualizado_em=cliente_updated_at,
                )
                self.db.add(novo_contato)

            ids_confirmados.append(str(c.id))

        await self.db.commit()
        return ids_confirmados
