"""Contact schemas with validation and sync payloads.

Includes lightweight validators to normalize phone numbers and ensure
timezone-aware datetimes (UTC) for offline-first synchronization.
"""

from __future__ import annotations

import datetime
import re
from enum import Enum
from typing import List, Optional
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    field_validator,
)


class TipoNumero(str, Enum):
    INSTITUCIONAL = "institucional"
    PUBLICO = "publico"


class ContatoBase(BaseModel):
    nome: str
    telefone: str
    email: Optional[EmailStr] = None
    tipo_numero: TipoNumero = TipoNumero.PUBLICO


class ContatoCreate(ContatoBase):
    """Payload when client creates a new contact. Client generates UUID."""

    id: UUID = Field(..., description="UUID generated by the client")


class ContatoUpdate(BaseModel):
    nome: Optional[str] = None
    telefone: Optional[str] = None
    email: Optional[EmailStr] = None
    tipo_numero: Optional[TipoNumero] = None


class ContatoResponse(ContatoBase):
    id: UUID
    criado_em: Optional[datetime.datetime] = None
    atualizado_em: datetime.datetime
    excluido: bool = False

    model_config = ConfigDict(from_attributes=True)


class ContatoSync(BaseModel):
    id: UUID
    nome: str
    telefone: str
    email: Optional[EmailStr] = None
    tipo_numero: TipoNumero
    atualizado_em: datetime.datetime
    excluido: bool = False

    @field_validator("atualizado_em")
    def ensure_timezone(cls, v: datetime.datetime) -> datetime.datetime:  # type: ignore[override]
        if v.tzinfo is None:
            return v.replace(tzinfo=datetime.timezone.utc)
        return v.astimezone(datetime.timezone.utc)


class SyncPayload(BaseModel):
    contatos: List[ContatoSync]
    ultima_sincronizacao: Optional[datetime.datetime] = None

    @field_validator("ultima_sincronizacao")
    def normalize_last_sync(cls, v: Optional[datetime.datetime]) -> Optional[datetime.datetime]:
        if v is None:
            return None
        if v.tzinfo is None:
            return v.replace(tzinfo=datetime.timezone.utc)
        return v.astimezone(datetime.timezone.utc)


class SyncResponse(BaseModel):
    sucesso: bool
    contatos_atualizados: List[UUID]
    error: Optional[List[str]] = None

    model_config = ConfigDict(from_attributes=True)


class IdPayload(BaseModel):
    """Payload containing an `id` for operations like delete."""

    id: UUID
