"""transforma_usuarios_em_permissoes

Revision ID: a36a895e7353
Revises: 
Create Date: 2026-06-23 12:59:27.708790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36a895e7353'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_nome', sa.String(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('contato_id', sa.String(), nullable=True),
    sa.Column('detalhes', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_id'), 'audit_trail', ['id'], unique=False)
    op.create_table('contatos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tipo_numero', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('excluido', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contatos_id'), 'contatos', ['id'], unique=False)
    op.create_index(op.f('ix_contatos_nome'), 'contatos', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('usuario_id_externo', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id_externo')
    )
    op.create_index(op.f('ix_usuarios_usuario_id_externo'), 'usuarios', ['usuario_id_externo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_usuario_id_externo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_contatos_nome'), table_name='contatos')
    op.drop_index(op.f('ix_contatos_id'), table_name='contatos')
    op.drop_table('contatos')
    op.drop_index(op.f('ix_audit_trail_id'), table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
